# -*- coding: utf-8 -*-
"""dicionários.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_MkqpJ2fQH6KCZuntU8BfM4dsTMCVMet

## Motivação 

- Para se conectar a uma rede wi-fi, você precisa de duas informações: o nome e a senha de acesso. Quando você vai acessar uma nova rede, você encontra uma lista de redes disponíveis:
"""

wifi_disponiveis = ['redel', 'cnx_cnx', 'uai-fi', 'r3d3']
print(wifi_disponiveis)

"""- E ai caso quisessemos indentificar as redes juntos com suas respectivas senhas, o list   não seria a melhor opção para trabalharmos.

- O que é um dicionário ?

  - Os dicionários são coleçãoes de itens e seus elementos são armazenados de forma não ordenada. Esse tipo de dado trabalha com um esquema de `chave e valor` 

- Exemplo: 

  `dic = {'chave' : 'valor'}`
"""

brasil = {'capital':'Brasília', 'idioma':'Português', 'populacao': 210}

print(brasil)
print(type(brasil))

"""- Criando dicionários compostos"""

cadastro = {
      'joao': {

          'nome': 'João Pedro',
          'ano_nascimento': 2003,
          'pais': {
                'pai': {
                'nome': '<nome-do-pai> Gonçalves',
                'ano_nascimento': 1975
                },
                'mae': {
                'nome': '<nome-da-mae> Lima',
                'ano_nascimento': 1979
                },
          }
      }
}
print(cadastro)

cadastro['joao']['pais']['mae']['ano_nascimento']

"""## Operações"""

credito = {'123': 750, '789': 980}

"""#### Acessando dicionários através de chaves

"""

score_123 = credito['123']
score_789 = credito['789']

print(score_123)
print(score_789)

"""#### Atualizando elementos através das suas chaves """

credito['123'] = 435
print(credito)

"""Adicionando um novo elmento
  - Para realizar essa operação basta adicionarmos um novo elemento key-value que ainda não exista.
"""

credito['456'] = 1000
print(credito)

"""## Métodos

- São métodos parecidos com os já trabalhados em outras estruturas de dados.
"""

artigo = dict(
    
    titulo = 'Modulo 02 | Python: Estrutura de dados',
    corpo = 'Topicos, Aulas, Listas, Conjuntos, Dicionários, ...',
    total_Caracteres=1530
)

"""### update

- Adiciona ou atualiza valores em dicionários

  `dict.update(dict)`
"""

print(artigo)
total_caracteres = artigo.update({'total_Caracteres': 7850})
print(artigo)

"""## pop 

- Ele remove elementos dos dicionários através de cahves.

  `dict.pop(key`
"""

print(artigo)
total_caracteres = artigo.pop('total_Caracteres')
print(artigo)

"""## Revisitando a motivação"""

wifi_disponiveis = []

rede = {'nome': 'redel', 'senha': 'cnx_cnx'}
wifi_disponiveis.append(rede)

rede = {'nome': 'uai-fi', 'senha': 'r3d3'}
wifi_disponiveis.append(rede)

print(wifi_disponiveis)